### ISSUE TITLE
"Incompatible character encodings" exception when a test throws an exception as a non-default character encoding

### ISSUE THREAD

**Issue by cbeer** [rspec/rspec-core#1662]
Using rspec 3.0.3 and ruby 2.1.2 (likely among others), this test case will crash rspec when it tries to report the results of the tests:

``` ruby
describe "Something that will break" do
  it "should fail" do
    expect(false).to eq true
  end

  it "should break rspec" do
    JSON.parse("©")
  end
end
```

https://github.com/cbeer/fully_formatted_failed_examples_failure/blob/master/spec/some_spec.rb

If you run that test, instead of getting the normal RSpec output, you get a stack trace, e.g.

``` console
$ be rspec
FF
/Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:192:in `block in fully_formatted': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:191:in `each'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:191:in `fully_formatted'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:94:in `block in fully_formatted_failed_examples'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:93:in `each'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:93:in `each_with_index'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/notifications.rb:93:in `fully_formatted_failed_examples'
    from /Volumes/TempStorage/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/formatters/base_text_formatter.rb:35:in `dump_failures'
```

It looks like, when `JSON.parse` is unable to parse a string, it returns an exception message as ASCII-8BIT:

```
irb(main):013:0> ex
=> #<JSON::ParserError: 757: unexpected token at '©'>
irb(main):015:0> ex.to_s.encoding
=> #<Encoding:ASCII-8BIT>
```

**Comment by sg552** [comment]
upgrade to 3.2.0 solved my problem.
