### ISSUE TITLE
undefined method `expect' for RSpec::ExampleGroups::User::Admin:Class (NoMethodError)

### ISSUE THREAD

**Issue by villins** [rspec/rspec-core#1770]
## spec

```
require 'rails_helper'

RSpec.describe User, :type => :model do
    let(:user) { FactoryGirl.create :user, email: 'exmail@gmail.com' }
    describe "admin?" do
       expect(3).to eq(3)
    end
end
```
## error

```
`block (2 levels) in <top (required)>': undefined method `expect' for RSpec::ExampleGroups::User::Admin:Class (NoMethodError)
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `module_exec'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `subclass'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:219:in `block in define_example_group_method'
    from /Users/Villins/outsource/weixin_yishu/spec/models/user_spec.rb:5:in `block in <top (required)>'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `module_exec'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `subclass'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:219:in `block in define_example_group_method'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/dsl.rb:41:in `block in expose_example_group_alias'
    from /Users/Villins/outsource/weixin_yishu/spec/models/user_spec.rb:3:in `<top (required)>'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `load'
    from /Users/Villins/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `<main>'
```

**Comment by eric7186** [comment]
I know this topic is closed but it really helped me understand why my expect() statements were error-ing and I haven't see another explanation as direct and clear. Thank you.

**Comment by hiteshranaut** [comment]
Just replace  
`expectations.syntax = :should`
with 
`expectations.syntax = [:should , :expect]`

in your spec_helper.rb
