### ISSUE TITLE
Exception when running test suite (3.3.1) – `build_scoped_id_for': undefined method `call' for :method:Symbol

### ISSUE THREAD

**Issue by zeeraw** [rspec/rspec-core#2008]
ruby: `2.2.0`
rails: `4.1.8`

```bash
rspec-support 3.3.0
rspec-core 3.3.1
rspec-expectations 3.3.0
rspec-mocks 3.3.1
rspec 3.3.0
rspec-rails 3.3.2
```

```bash
/Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/metadata.rb:179:in `build_scoped_id_for': undefined method `call' for :method:Symbol (NoMethodError)
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/metadata.rb:155:in `populate_location_attributes'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/metadata.rb:131:in `populate'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/metadata.rb:249:in `create'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:388:in `set_it_up'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:362:in `subclass'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
  from /Users/xxx/Projects/xxx/xxx/spec/models/card_spec.rb:7:in `block in <top (required)>'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:363:in `module_exec'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:363:in `subclass'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
  from /Users/xxx/Projects/xxx/xxx/spec/models/card_spec.rb:3:in `<top (required)>'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1325:in `each'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:102:in `setup'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:88:in `run'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:73:in `run'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:41:in `invoke'
  from /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/exe/rspec:4:in `<top (required)>'
  from /Users/xxx/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
  from /Users/xxx/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
```

**Comment by myronmarston** [comment]
Can you provide the contents of `spec/models/card_spec.rb`?  I've got multiple projects on RSpec 3.3 and don't get this error so there's something different about your specs.

**Comment by myronmarston** [comment]
There's nothing actionable we can do without more info, so I'm going to close this due to the lack of response.  I'll gladly re-open if @zeeraw (or anyone else who has this problem) can provide additional info.

**Comment by dgmstuart** [comment]
@myronmarston @zeeraw looks like this is an incompatibility with the https://github.com/zeeraw/spryte gem: an empty spec file causes the error, and deleting references to spryte from the rails_helper causes the model specs (which don't use spryte) to pass. 

This one can stay closed. I'll raise an issue on the spryte repo.

**Comment by dgmstuart** [comment]
@myronmarston the issue turns out to be related to this commit in RSpec Core: "[Add ids to examples and groups](https://github.com/rspec/rspec-core/commit/057e729f087660a45dd9569f7888fca28d6380ae)"

...which adds a call to `superclass.method`:
```ruby
@metadata = Metadata::ExampleGroupHash.create(
  superclass_metadata, user_metadata,
  superclass.method(:next_runnable_index_for),
  description, *args, &example_group_block
)
```

The issue being that the Spryte gem defines a DSL [which adds a `method` method](https://github.com/zeeraw/spryte/blob/63baec5b8da205e20623604c73eb016ebd55d287/lib/spryte/rspec/macros.rb#L27-L29) (as in 'http method': get, post etc) and thus nameclashes with the call to `Object#method` being made here.

I guess this doesn't reasonably represent an issue with RSpec but I thought it was worth running past you.

**Comment by myronmarston** [comment]
It would be fairly easy to work around this in RSpec by passing `lambda { |file| superclass.next_runnable_index_for(file) }` instead of `superclass.method(:next_runnable_index_for)` (are you interested in submitting a PR to do that?) but Spryte may want to rename it's `method` method to `http_method`.  In general, RSpec needs to be able to use Ruby's meta protocols (e.g. the `method` method, `respond_to?`, etc) freely and we're often willing to work around such issues on a one-off basis but Spryte is playing with fire to redefine `method` like that.

**Comment by dgmstuart** [comment]
@myronmarston Many thanks for your thoughtful response. I've submitted a PR for this on core: https://github.com/rspec/rspec-core/pull/2112

But I agree that Spryte should address this at source as well - I'll submit a PR there as well.
