### ISSUE TITLE
html_formatter.rb:141:in `extra_failure_content': undefined method `map' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by McRip** [rspec/rspec-core#2018]
RSpec crashes here and in the Output it says 'Couldn't get snippet for'. Any ideas how to fix this?

Ruby 2.2.2
Rspec 3.3.1

Full Stacktrace:

```
/Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/formatters/html_formatter.rb:141:in `extra_failure_content': undefined method `map' for nil:NilClass (NoMethodError)
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/formatters/html_formatter.rb:78:in `example_failed'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/reporter.rb:184:in `block in notify'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/reporter.rb:183:in `each'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/reporter.rb:183:in `notify'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/reporter.rb:135:in `example_failed'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example.rb:404:in `finish'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example.rb:363:in `fail_with_exception'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:529:in `block in run'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:567:in `each'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:567:in `for_filtered_examples'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:571:in `block in for_filtered_examples'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:569:in `each'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:569:in `for_filtered_examples'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:571:in `block in for_filtered_examples'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:569:in `each'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:569:in `for_filtered_examples'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:529:in `rescue in run'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/example_group.rb:534:in `run'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:115:in `map'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/reporter.rb:77:in `report'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:113:in `run_specs'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:89:in `run'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/gems/rspec-core-3.3.1/exe/rspec:4:in `<top (required)>'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/bin/rspec:23:in `load'
	from /Users/moritzkroger/Documents/dev/ace/vendor/ruby/2.2.0/bin/rspec:23:in `<main>'
```

**Comment by myronmarston** [comment]
It appears that in your case you've got an exception where `exception.backtrace` returns `nil` rather than an array as expected.  I'm not sure how you're getting that (the only way I can find to simulate it is to explicitly call `exception.set_backtrace(nil)`, which would be an odd thing to do in any context besides that of a test that is simulating an exception without a backtrace...) but I've got a fix in #2023 if you want to try it out.
