### ISSUE TITLE
Random errors running rspec on rspec-core(master)

### ISSUE THREAD

**Issue by bennacer860** [rspec/rspec-core#2048]
I am trying to run rspec on rspec-core and it is failing miserably on my machine.

```
cer@fennec ~/projects/ruby-for-good/rspec-core-2 (master*) $ rspec
Run options:
  include {:focus=>true}
  exclude {:ruby=>#<Proc:./spec/spec_helper.rb:106>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 55367
..........................................................................................................................................................
..........................................................................................................................................................
................................................................................................*.........................................................
..........................................................................................................................................................
..........................................................................................................................................................
..........................................................................................................................................................
..........................................................................................................................................................
................FF........................................................................................................................................
..........................................................................................................................................................
..........................................................................................................................................................
..........................................................................................................................................................
............................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)
 1) RSpec::Core::Metadata for an example points :example_group to the same hash object as other examples in the same group
     # Cannot maintain this and provide full `:example_group` backwards compatibility (see GH #1490):(
     Failure/Error: expect(b[:description]).to eq("new description")

       expected: "new description"
            got: "group"
  expected: "new description"                                                                                                                [0/1893]
            got: "group"

       (compared using ==)
     # ./spec/rspec/core/metadata_spec.rb:138:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

Failures:

  1) RSpec::Core::Runner.running_in_drb? returns true if drb server is started with 127.0.0.1
     Failure/Error: expect(RSpec::Core::Runner.running_in_drb?).to be_truthy
       expected: truthy value
            got: false
     # ./spec/rspec/core/runner_spec.rb:120:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  2) RSpec::Core::Runner.running_in_drb? returns true if drb server is started with localhost
     Failure/Error: expect(RSpec::Core::Runner.running_in_drb?).to be_truthy
       expected: truthy value
            got: false
     # ./spec/rspec/core/runner_spec.rb:126:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

Finished in 9.39 seconds (files took 0.68716 seconds to load)
1802 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/rspec/core/runner_spec.rb:117 # RSpec::Core::Runner.running_in_drb? returns true if drb server is started with 127.0.0.1
rspec ./spec/rspec/core/runner_spec.rb:123 # RSpec::Core::Runner.running_in_drb? returns true if drb server is started with localhost
```

My machine specs are:
```
rbennacer@fennec ~/projects/ruby-for-good/rspec-core-2 (master*) $ rvm -v
rvm 1.26.3 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
rbennacer@fennec ~/projects/ruby-for-good/rspec-core-2 (master*) $ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
rbennacer@fennec ~/projects/ruby-for-good/rspec-core-2 (master*) $ rspec -v
3.4.0.pre
```
And i am using `10.10.4 (14E46)`.

I don't really understand what are these errors since i have not been able to reproduce them in another machine

**Comment by JonRowe** [comment]
Can you reproduce them by using the same seed on your machine?

**Comment by jackscotti** [comment]
I get one pending and 15 failures: 

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) RSpec::Core::Metadata for an example points :example_group to the same hash object as other examples in the same group
     # Cannot maintain this and provide full `:example_group` backwards compatibility (see GH #1490):(
     Failure/Error: expect(b[:description]).to eq("new description")

       expected: "new description"
            got: "group"

       (compared using ==)
     # ./spec/rspec/core/metadata_spec.rb:138:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

Failures:

  1) Persistence failures when `config.example_status_persistence_file_path` is configured to an invalid file path (e.g. spec/spec_helper.rb/examples.txt) emits a helpful warning to the user, indicating we cannot write to it, and still runs the spec suite
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  2) Persistence failures when `config.example_status_persistence_file_path` is configured to a file path for which we lack permissions emits a helpful warning to the user, indicating we cannot read from it, and still runs the spec suite
     Got 1 failure and 1 other error:

     2.1) Failure/Error: expect(last_cmd_stderr).to include(*expected_snippets)
            expected "" to include "WARNING: Could not read", "spec/examples.txt", "config.example_status_persistence_file_path", and "Errno:"
          # ./spec/integration/persistence_failures_spec.rb:64:in `block (4 levels) in <top (required)>'
          # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
          # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

     2.2) Failure/Error: Unable to find matching line from backtrace
          RuntimeError:
            Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
            The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
            The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
          # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
          # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  3) command line --order defined on CLI with --order rand in .rspec overrides --order rand with --order defined
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "remove_file" is deprecated. Use "remove" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  4) command line --order rand:SEED runs the examples and groups in the same order each time
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  5) command line --seed SEED forces '--order rand' and runs the examples and groups in the same order each time
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  6) command line --seed SEED runs examples in the same order, regardless of the order in which files are given
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  7) command line when a custom order is configured orders the groups and examples by the provided strategy
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "remove_file" is deprecated. Use "remove" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  8) command line --order rand runs the examples and groups in a different order each time
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  9) Filtering prints a rerun command for shared examples in external files that works to rerun
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
       The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
     # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  10) Filtering passing a line-number filter trumps exclusions, except for :if/:unless (which are absolute exclusions)
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  11) Filtering with a shared example containing a context in a separate file runs the example nested inside the shared
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  12) Filtering passing example ids at the command line selects matching examples
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  13) Filtering passing example ids at the command line selects matching example groups
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  14) Filtering passing a line-number-filtered file and a non-filtered file applies command line tag filters only to files that lack a line number filter
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  15) Filtering passing a line-number-filtered file and a non-filtered file applies the line number filtering only to the filtered file, running all specs in the non-filtered file except excluded ones
      Failure/Error: Unable to find matching line from backtrace
      RuntimeError:
        Warnings were generated: The use of "clean_current_dir" is deprecated. Use "clean_current_directory" instead
        The use of "in_current_dir" is deprecated. Use "in_current_directory" instead
      # ./spec/support/sandboxing.rb:14:in `block (3 levels) in <top (required)>'
      # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

Finished in 11.6 seconds (files took 0.89676 seconds to load)
1797 examples, 15 failures, 1 pending
```

**Comment by JonRowe** [comment]
That looks like an aruba issue, can you try using `bundle exec` to run specs so the correct version is picked up?

**Comment by jackscotti** [comment]
Done, nothing changed.

**Comment by samphippen** [comment]
@jackscotti @bennacer860 if you do a fresh clone of https://github.com/rspec/rspec-dev and run [these setup steps](https://github.com/rspec/rspec-dev#rspec-dev). Do you get all green? If so, we're good and can close, otherwise there's some weird underlying issue here. It's worth noting, our CI is all green, and this is most likely a machine-specific issue, however.

**Comment by jackscotti** [comment]
All green :+1:

**Comment by samphippen** [comment]
Thanks.
