### ISSUE TITLE
'block in shellsplit' Error

### ISSUE THREAD

**Issue by gxespino** [rspec/rspec-core#2053]
Getting a random error when trying to run rake:

```
/Users/GMAC/.rvm/rubies/ruby-2.2.2/bin/ruby -I/Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib:/Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-support-3.3.0/lib /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/GMAC/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/shellwords.rb:75:in `block in shellsplit': Unmatched double quote: "\" Press ? for help" (ArgumentError)
        from /Users/GMAC/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/shellwords.rb:73:in `scan'
        from /Users/GMAC/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/shellwords.rb:73:in `shellsplit'
        from /Users/GMAC/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/shellwords.rb:189:in `shellsplit'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/flat_map.rb:7:in `each'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/flat_map.rb:7:in `flat_map'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/flat_map.rb:7:in `flat_map'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:164:in `args_from_options_file'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:151:in `options_from'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:147:in `global_options'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:118:in `file_options'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:43:in `organize_options'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:13:in `initialize'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:62:in `new'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:62:in `run'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
/Users/GMAC/.rvm/rubies/ruby-2.2.2/bin/ruby -I/Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/lib:/Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-support-3.3.0/lib /Users/GMAC/.rvm/gems/ruby-2.2.2@myapp/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed


```

Any ideas?

**Comment by myronmarston** [comment]
Can you paste the contents of your `~/.rspec` file?

**Comment by gxespino** [comment]
Thanks for leading me in the right direction. Apparently created a .rspec file in my root that had my NERDTree menu pasted into it (thats what I get for trying to learn Vim). Deleted the .rspec and everything works again!
