### ISSUE TITLE
stack level too deep when stubbing respond_to?

### ISSUE THREAD

**Issue by nesQuick** [rspec/rspec-core#2067]
Hey there,
I'm encountering a issue when I try to test a method using `respond_to?`

here is a stripped down example
```ruby
require "spec_helper"

class Asset
  def render(mode:, **context)
    render_method = "render_for_#{mode.to_s}"
    if self.respond_to? render_method
      self.send(render_method, context)
    else
      return self.content
    end
  end
end

RSpec.describe Asset do

  let(:context) { double('context') }

  it 'calls render_content_for_<mode> if exist' do
    expected_content = 'HTML CONTENT'

    expect(subject).to receive(:respond_to?).with('render_for_system').and_return(true)
    expect(subject).to receive(:render_for_system).with(context: context).and_return(expected_content)

    content = subject.render mode: :system, context: context

    expect(content).to eq expected_content
  end
end
```

I'm seeing the following error + trace:

```
💀  naked-lunch git:(rspec) ✗ rspec spec/stack_level_issue_spec.rb --backtrace
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 35732

Asset
  calls render_content_for_<mode> if exist (FAILED - 1)

Failures:

  1) Asset calls render_content_for_<mode> if exist
     Failure/Error: expect(subject).to receive(:render_for_system).with(context: context).and_return(expected_content)
     SystemStackError:
       stack level too deep
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-expectations-3.3.1/lib/rspec/matchers.rb:1001:in `block in <module:Matchers>'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/matcher_definition.rb:28:in `call'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/matcher_definition.rb:28:in `block in is_a_matcher?'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/matcher_definition.rb:28:in `any?'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/matcher_definition.rb:28:in `is_a_matcher?'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:36:in `prepare_for_inspection'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-support-3.3.0/lib/rspec/support/object_formatter.rb:8:in `format'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:329:in `block in arg_list'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:329:in `map'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:329:in `arg_list'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:325:in `format_args'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:334:in `block in format_received_args'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:333:in `each'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:333:in `map'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:333:in `format_received_args'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:251:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `join'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:77:in `default_error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:252:in `error_message'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/message_expectation.rb:490:in `raise_unexpected_message_args_error'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:187:in `message_received'

     ........... repeats a bunch of times

     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/proxy.rb:321:in `message_received'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:156:in `proxy_method_invoked'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:178:in `initialize'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:198:in `new'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:198:in `for'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:117:in `block in initialize'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:39:in `yield'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:39:in `ensure_implemented'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:34:in `add_message_expectation'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:96:in `setup_method_substitute'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:84:in `setup_mock_proxy_method_substitute'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:24:in `setup_expectation'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/stack_level_issue_spec.rb:22:in `block (2 levels) in <top (required)>'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/ole/.gem/ruby/2.2.2/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
     # ./bin/rspec:16:in `load'
     # ./bin/rspec:16:in `<main>'

Top 1 slowest examples (0.04247 seconds, 98.4% of total time):
  Asset calls render_content_for_<mode> if exist
    0.04247 seconds ./spec/stack_level_issue_spec.rb:18

Finished in 0.04317 seconds (files took 0.09604 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/stack_level_issue_spec.rb:18 # Asset calls render_content_for_<mode> if exist

Randomized with seed 35732
```

or maybe I'm just doing it wrong, but have no idea what to do differently.

Any ideas?

**Comment by JonRowe** [comment]
You don't need to do this:
> `expect(subject).to receive(:respond_to?).with('render_for_system').and_return(true)`

As setting up the stub will cause `respond_to?` to return `true` anyway.

**Comment by JonRowe** [comment]
That said I wouldn't expect this to blow up and it does so I'll look into it, but for now simply removing the `respond_to?` expectation will make your spec pass (and just don't stub the `render_for_system` method for the other pathway)

**Comment by nesQuick** [comment]
Thanks for getting back so quickly, when I remove `expect(subject).to receive(:respond_to?).with('render_for_system').and_return(true)` I see the following issue:

```
  naked-lunch git:(rspec) ✗ bundle exec rspec spec/stack_level_issue_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Asset
  calls render_content_for_<mode> if exist (FAILED - 1)

Failures:

  1) Asset calls render_content_for_<mode> if exist
     Failure/Error: expect(subject).to receive(:render_for_system).with(context: context).and_return(expected_content)
       #<Asset:0x007fc3b38ce9b0> does not implement: render_for_system
     # ./spec/stack_level_issue_spec.rb:22:in `block (2 levels) in <top (required)>'

Top 1 slowest examples (0.00518 seconds, 91.0% of total time):
  Asset calls render_content_for_<mode> if exist
    0.00518 seconds ./spec/stack_level_issue_spec.rb:18

Finished in 0.0057 seconds (files took 0.08396 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/stack_level_issue_spec.rb:18 # Asset calls render_content_for_<mode> if exist
```

**Comment by nesQuick** [comment]
Just to clarify my use case: this is kind of a base object, the method `render_for_system` will be implemented in a subclass.

**Comment by JonRowe** [comment]
Hmm I can't reproduce your second failure, in a copy paste of your code commenting out the expectation on respond_to causes the test to pass,

**Comment by myronmarston** [comment]
Looks like a verifying double failure since your base class does not implement that method?

Personally, mocking seems like a code smell here. If the class is meant to be subclassed where the subclass implements certain methods, I'd define an example subclass (using Class.new) inline that defines whatever a subclass is meant to. 

After all, a big point of TDD is forcing yourself to use the APIs you've defined in your test so you see how it feels to use it...and the intended usage here is to define a subclass so I would do that.

**Comment by JonRowe** [comment]
Ah true, my sandbox doesn't turn on verifying partial doubles, I agree with @myronmarston here, additionally in the pattern where you override the base class to provide differing method implementations (like with a render method) it's traditional to provide a base no-op implementation also

**Comment by nesQuick** [comment]
Thanks for your elaboration on this @myronmarston I definitely see your point and agree with it, also I'm giving the inline class a spin. But even though would you consider fixing it?

@JonRowe my point against a no-op implementation is that every subclass can have different render modes, and in order to keep this flexible I had the implementation in place where the default would just pass the raw content and any supportet render mode by the class *would just work*:tm: 

thanks for your input! :sparkling_heart:

**Comment by samphippen** [comment]
I feel like stubbing respond_to? should work. The kernel rebinding trick in RSpec::Support.method_handle_for would work for stubbing `method`, can we just apply it here?
