### ISSUE TITLE
US-ASCII (ArgumentError) error after updating to 3.4.x

### ISSUE THREAD

**Issue by brbrr** [rspec/rspec-core#2180]
Running failing tests would raise strange error:
`$ bundle exec rspec spec/user/user_spec.rb:257`

```
3 examples, 3 failures

Failed examples:

rspec ./spec/user/user_spec.rb:257 # User ./signer should be possible to re-sign after attempt with invalid pin code
rspec ./spec/user/user_spec.rb:257 # User ./signer should be possible to re-sign after attempt with invalid pin code
rspec ./spec/user/user_spec.rb:257 # User ./signer should be possible to re-sign after attempt with invalid pin code

/Users/brbrr/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/source.rb:23:in `split': invalid byte sequence in US-ASCII (ArgumentError)

        from /Users/brbrr/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/source.rb:23:in `lines'
        from /Users/brbrr/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/formatters/snippet_extractor.rb:50:in `expression_lines'
```

I'm running single example which have before :example & :context hooks
with rspec 3.3.x everything works smooth.

**Comment by myronmarston** [comment]
Does `spec/user/user_spec.rb` contain non-ascii characters?  Have you tagged the file with `# encoding: utf-8` at the top of the file so Ruby knows to treat it as UTF-8?  What are `Encoding.default_internal` and `Encoding.default_external` in your environment?

**Comment by brbrr** [comment]
```
[1] pry(#<RSpec::ExampleGroups::User::Signer>)> Encoding.default_internal
=> nil
[2] pry(#<RSpec::ExampleGroups::User::Signer>)> Encoding.default_external
=> #<Encoding:US-ASCII>
```

adding `# encoding: utf-8` not fixing that issue. 

but yeah, I got file(not a spec) where I had russian comment.
So it's resolved for me.

**Comment by myronmarston** [comment]
If you set `Encoding.default_external = "UTF-8"` it should also fix it.  I don't think there's any good reason to have your `default_external` encoding set to `US-ASCII`, especially because all valid ascii is valid UTF-8.

**Comment by JonRowe** [comment]
@myronmarston It's a bit weird but it was the default at one point, this must be an artifact of his environment, but we should probably still fix this literal.

**Comment by brbrr** [comment]
I'm using English MAC OS 10.11.3 (I was switched from Russian language some time ago).
`rbenv` with
```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```
Not sure what more to say regarding my env.

**Comment by JonRowe** [comment]
Can you run `env` and list your environment vars?

**Comment by brbrr** [comment]
```
$ env
MANPATH=/Users/brbrr/.nvm/versions/node/v5.1.0/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/usr/local/MacGPG2/share/man:/Library/Developer/CommandLineTools/usr/share/man
TERM_PROGRAM=Apple_Terminal
ANDROID_HOME=/Users/brbrr/Documents/Development/Utils/android-sdk-macosx
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/6g/r7_x32mn4456n4z_5mdl4n4r0000gn/T/
NVM_PATH=/Users/brbrr/.nvm/versions/node/v5.1.0/lib/node
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.DuzrhaHA41/Render
TESSDATA_PREFIX=/usr/local/share/
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=9FA51CF7-EF40-4B35-AC72-31AB00BB2A04
NVM_DIR=/Users/brbrr/.nvm
USER=brbrr
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.os0Kv6YwUw/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LSCOLORS=ExFxBxDxCxegedabagacad
PATH=/Users/brbrr/.nvm/versions/node/v5.1.0/bin:/Users/brbrr/.rbenv/shims:/usr/local/bin:/Users/brbrr/.rbenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/smlnj/bin:/usr/local/share/npm/bin/:/Users/brbrr/Documents/Development/Utils/android-sdk-macosx/build-tools:/Users/brbrr/Documents/Development/Utils/android-sdk-macosx/platform-tools:/Users/brbrr/Documents/Development/Utils/android-sdk-macosx/tools
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/brbrr
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
ANDROID_SDK=/Users/brbrr/Documents/Development/Utils/android-sdk-macosx
XPC_FLAGS=0x0
PS1=\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\] \W \[\]$git_branch\[\]$git_dirty\[\]$ 
XPC_SERVICE_NAME=0
GITAWAREPROMPT=/Users/brbrr/.bash/git-aware-prompt
SHLVL=1
HOME=/Users/brbrr
LOGNAME=brbrr
LC_CTYPE=UTF-8
NVM_BIN=/Users/brbrr/.nvm/versions/node/v5.1.0/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
_=/usr/bin/env
```

**Comment by sl4m** [comment]
Does `ruby` default to `US-ASCII` if `LANG` is not defined?

**Comment by JonRowe** [comment]
That's exactly what's happening:

```ruby
~$ ruby -e 'puts Encoding.default_external'
UTF-8
~$ echo $LANG
en_AU.UTF-8
~$ unset LANG
~$ echo $LANG

~$ ruby -e 'puts Encoding.default_external'
US-ASCII
```
