### ISSUE TITLE
Test execution failing with latest 3.4.4

### ISSUE THREAD

**Issue by brbrr** [rspec/rspec-core#2213]
After updating rspec-core from 3.3.2 my jenkins tests starts to fail with very strange error. They return that error when switching to next file. Same tests are passing on my local mac.

Running tests with : `REST_ENV=test bundle exec rspec spec -t smoke -t ~prod`, with rspec 3.3.0 they works well. 

Not sure is it relevent, but in my describe/context/it blocks I use parameters like ` feature: 'MARS-1546'` which is used by `allure-rspec` (turned off)

full stack trace:

```
/usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/source.rb:28:in `require': cannot load such file -- ripper (LoadError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/source.rb:28:in `ast'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/source.rb:45:in `nodes_by_line_number'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:120:in `location_nodes_at_beginning_line'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:98:in `expression_node'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:90:in `line_range_of_location_nodes_in_expression'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:59:in `line_range_of_expression'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:44:in `expression_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:33:in `extract_expression_lines_at'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:209:in `read_failed_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:160:in `failure_slash_error_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:147:in `block in failure_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:146:in `tap'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:146:in `failure_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:32:in `colorized_message_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:231:in `formatted_message_and_backtrace'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:84:in `fully_formatted_lines'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:76:in `fully_formatted'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:200:in `fully_formatted'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fuubar-2.0.0/lib/fuubar.rb:67:in `example_failed'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:140:in `example_failed'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:452:in `finish'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:410:in `fail_with_exception'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:550:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:591:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:591:in `for_filtered_examples'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:595:in `block in for_filtered_examples'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:593:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:593:in `for_filtered_examples'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:595:in `block in for_filtered_examples'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:593:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:593:in `for_filtered_examples'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:550:in `rescue in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:556:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/bin/rspec:23:in `load'
	from /usr/local/bin/rspec:23:in `<main>'
```

**Comment by myronmarston** [comment]
In RSpec 3.4 we introduced a new feature -- [multiline failure snippets](http://rspec.info/blog/2015/11/rspec-3-4-has-been-released/#multi-line-code-snippets) which uses [ripper](http://ruby-doc.org/stdlib-2.2.0/libdoc/ripper/rdoc/Ripper.html) under the covers.  Ripper is part of the ruby standard library and has been since at least Ruby 1.9.2.  RSpec assumes that if you're on MRI > 1.9.2 that ripper is available to load since it is part of the standard library.

In your case, that's failing.  Ripper appears to be unavailable even though it's been part of the standard library for years.

How did you install ruby in such a way that parts of the standard library are missing?

**Comment by JonRowe** [comment]
We could handle a `LoadError` from the require ripper as "not supporting" ripper

**Comment by myronmarston** [comment]
> We could handle a LoadError from the require ripper as "not supporting" ripper

That would work.

**Comment by mrageh** [comment]
@JonRowe should we really handle missing parts of Ruby's standard library on someone's local version of Ruby?

**Comment by JonRowe** [comment]
@mrageh normally I'd suggest we don't go out of our way to do so, but in this case we already have the functionality to handle this, and it's completely non-essential to the running specs.

**Comment by samphippen** [comment]
Given that travis will not provide us a Ruby that has ripper missing, I don't think we should support this, while RSpec has a "support all the things" mentality, I think a ruby that is misconfigured isn't a thing that we should support. @rspec/rspec can we close?

**Comment by myronmarston** [comment]
I agree with closing.  If @brbrr provides more detail about his ruby installation (which explains why part of the standard lib is missing) we can reopen and reconsider.

**Comment by brbrr** [comment]
I don't have all details about installation, but it was installed on VM with Debian Wheezy, I suppose through apt. (or compiled from sources).

**Comment by JonRowe** [comment]
It would be troubling if the apt package was broken like this, but theres still not much we can do about that.

**Comment by robotmay** [comment]
Not entirely sure how, but I've managed to get to the same situation on a fresh Ubuntu 16.04 installation, installing Ruby 2.3.2 via ruby-install. So latest everything, and compiled Ruby on the machine, and ripper doesn't appear to be present. I'm looking into it, but it does seem to be easier to cause this than previously thought :\

**Comment by JonRowe** [comment]
@robotmay you might wish to raise that as an issue with the ruby folk, they might be willing to patch it to warn in that scenario!

**Comment by robotmay** [comment]
Thanks @JonRowe! I came across the solution via a bug filed on a development version of Ruby, but I don't think the fix has been backported yet so I'll see if I can get someone's attention on it :D

**Comment by mvz** [comment]
@robotmay I think ruby-install should also include bison in the list of dependencies to install.

**Comment by robotmay** [comment]
Oh sweet, nice find!
