### ISSUE TITLE
Can't find method in ApplcationHelper

### ISSUE THREAD

**Issue by Draveness** [rspec/rspec-core#2217]
I use RSpec to test posts_controller, and call a method in ApplicationHelper

```
RSpec.describe Api::V1::PostsController, type: :controller do

  render_views

  before(:each) do
    create(:user_with_posts, posts_count: 40)
  end

  describe "posts#index API" do
    it "is true" do

      get :index, format: :json

      json = JSON.parse(response.body)

      puts json

    end
  end
end
```

posts_controller.rb

```
class Api::V1::PostsController < Api::V1::BaseController
  def index
    @posts = paginate(Post.all)
  end
end
```

index.json.builder

```
json.paginate_meta do
  paginate_meta_attributes(json, @posts)
end

json.posts do
  json.array! @posts do |post|
    json.(post, :id, :title, :content)
    json.author do
      json.(post.author, :id, :email, :nickname)
    end
  end
end
```

application_helper.rb

```
module ApplicationHelper

  def paginate_meta_attributes(json, object)
    json.(object,
          :current_page,
          :next_page,
          :prev_page,
          :total_pages,
          :total_count)
  end
end
```

And when I run rspec

```
  1) Api::V1::PostsController posts#index API is true
     Failure/Error: paginate_meta_attributes(json, @posts)

     ActionView::Template::Error:
       undefined method `paginate_meta_attributes' for #<#<Class:0x007f8286389c70>:0x007f8286389310>
     # ./app/views/api/v1/posts/index.json.jbuilder:2:in `block in _app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:38:in `block in set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:266:in `block in _merge_block'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:305:in `_scope'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:266:in `_merge_block'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:38:in `set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder/jbuilder_template.rb:74:in `set!'
     # /Users/apple/.rvm/gems/ruby-2.1.1/gems/jbuilder-2.4.1/lib/jbuilder.rb:66:in `method_missing'
     # ./app/views/api/v1/posts/index.json.jbuilder:1:in `_app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960'
     # ./spec/controllers/posts_controller_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `paginate_meta_attributes' for #<#<Class:0x007f8286389c70>:0x007f8286389310>
     #   ./app/views/api/v1/posts/index.json.jbuilder:2:in `block in _app_views_api_v__posts_index_json_jbuilder__4514465265669488631_70099287053960
```

I don't why, but I define this method in ApplicationHelper, how to solve this problem.

Thx a lot.

**Comment by JonRowe** [comment]
Helper inclusion is determined by Rails I believe, what version are you using? Also please note this is the wrong repository to open rspec-rails issues. This repo is only for rspec-core issues.
