### ISSUE TITLE
Ruby 2.3 squiggly heredoc causes exceptions when generating failure messages

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-core#2238]
Using the new Ruby 2.3 squiggly heredoc causes problems when formatting failure messages:

```
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:70:in `block in on_heredoc_dedent': undefined method `event' for #<Array:0x007fdffb063668> (NoMethodError)
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:69:in `each'
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:69:in `on_heredoc_dedent'
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:61:in `parse'
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:61:in `parse'
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:55:in `lex'
        from /.rubies/ruby-2.3.0/lib/ruby/2.3.0/ripper/lexer.rb:44:in `lex'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/source.rb:38:in `tokens'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/source.rb:52:in `tokens_by_line_number'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:74:in `block in unclosed_tokens_in_line_range'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/flat_map.rb:7:in `each'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/flat_map.rb:7:in `flat_map'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/flat_map.rb:7:in `flat_map'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:73:in `unclosed_tokens_in_line_range'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:60:in `line_range_of_expression'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:44:in `expression_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/snippet_extractor.rb:33:in `extract_expression_lines_at'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:209:in `read_failed_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:160:in `failure_slash_error_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:147:in `block in failure_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:146:in `tap'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:146:in `failure_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:32:in `colorized_message_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:231:in `formatted_message_and_backtrace'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:84:in `fully_formatted_lines'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/exception_presenter.rb:76:in `fully_formatted'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:200:in `fully_formatted'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `each'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `each_with_index'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/formatters/base_text_formatter.rb:33:in `dump_failures'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:160:in `block in finish'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:175:in `close_after'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:156:in `finish'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:79:in `report'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /.gem/ruby/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /.gem/ruby/2.3.0/bin/rspec:23:in `load'
        from /.gem/ruby/2.3.0/bin/rspec:23:in `<main>'
```

Here is a spec that reproduces the issue:

```ruby
RSpec.describe "Ruby 2.3 squiggaly heredoc" do

  let(:heredoc) {
    <<~DOC
      New Ruby 2.3 HEREDOC syntax!
      It strips leading whitespace but only as deep as the first line
          so this is indented
      No need for ActiveSupport `strip_heredoc`
    DOC
  }

  it "causes an exception on failing specs" do
    expect(1).to eq(2)
  end

end
```

Instead if I use `<<-DOC.strip_heredoc` as provided by ActiveSupport everything works fine.

**Comment by JonRowe** [comment]
This is a duplicate, just looking for the issue now, and it's being fixed upstream.

**Comment by cupakromer** [comment]
(>ლ) I forgot to remove the default "open" filter when I searched. Thanks!
