### ISSUE TITLE
Rake task regression? Runs 0 examples since RSpec 3.4.0

### ISSUE THREAD

**Issue by xmik** [rspec/rspec-core#2303]
In a `Rakefile.rb` I have a rake task:
```ruby
::RSpec::Core::RakeTask.new(:spec) do |task|
 task.rspec_opts      = "--tty --color --format documentation --format h "\
  "--out ./rspec.html --pattern #{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb"
end
```
When using RSpec 3.3.0, all is fine, all examples are run. But when I use RSpec 3.4.0, there are 0 examples run. I found out that there is the new way how to invoke rspec rake task:
```ruby
desc 'Run RSpec tests'
RSpec::Core::RakeTask.new(:spec) do |task, args|
  task.rspec_opts      = '--tty --color --format documentation --format h --out ./rspec.html'
  task.pattern         = "#{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb"
end
```

Was such change intended or is it a regression?

**Comment by myronmarston** [comment]
> I found out that there is the new way how to invoke rspec rake task:

FWIW, the `pattern` option was present in RSpec 2.0, every release since, and may have even predated RSpec 2 (but this repo does not have the 1.x history so it's hard for me to check).

That said, `rspec_opts` is meant to support any arbitrary CLI options, so it _should_ work to pass `--pattern` even though it's not the recommended way.  I definitely consider this a regression.

Any chance you could put together a repo that reproduces this so we can use it as a test bed for tracking down the issue?

**Comment by JonRowe** [comment]
I tried this out on `3.5.0` and couldn't reproduce so it'd definitely be helpful to have a reproduction case.

**Comment by xmik** [comment]
Thank you for fast responses :) I reproduced the problem here: https://github.com/xmik/gem-rspec-rake-task-reproduction . This is crucial: this issue is not reproduced when tests are in `{my_gem_dir}/spec/` directory.

**Comment by myronmarston** [comment]
Thanks for putting together that repo!  Unfortunately, when I run the `old` task on either RSpec version, I get a different error:

```
➜  gem-rspec-rake-task-reproduction git:(master) BUNDLE_GEMFILE="./Gemfile.3-3-0" bundle exec rake old
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
/Users/myron/.rubies/ruby-2.1.5/bin/ruby -I/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib:/Users/myron/.rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb
/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load': cannot load such file -- /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/spec/**/*_spec.rb (LoadError)
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
/Users/myron/.rubies/ruby-2.1.5/bin/ruby -I/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/lib:/Users/myron/.rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb failed
➜  gem-rspec-rake-task-reproduction git:(master) BUNDLE_GEMFILE="./Gemfile.3-4-0" bundle exec rake old
/Users/myron/.rubies/ruby-2.1.5/bin/ruby -I/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib:/Users/myron/.gem/ruby/2.1.5/gems/rspec-support-3.4.1/lib /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb
/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load': cannot load such file -- /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/spec/**/*_spec.rb (LoadError)
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
/Users/myron/.rubies/ruby-2.1.5/bin/ruby -I/Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/lib:/Users/myron/.gem/ruby/2.1.5/gems/rspec-support-3.4.1/lib /Users/myron/.gem/ruby/2.1.5/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /Users/myron/code/rspec-scratch/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb failed
```

**Comment by myronmarston** [comment]
OK, looks like I can fix that error by applying this diff:

``` diff
diff --git a/Rakefile b/Rakefile
index 36e2bbc..9a9bb35 100644
--- a/Rakefile
+++ b/Rakefile
@@ -1,6 +1,7 @@
 require 'rspec/core/rake_task'
+require 'shellwords'
 
-tests_pattern = "#{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb"
+tests_pattern = "#{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb".shellescape
 
 desc 'Run RSpec tests'
 ::RSpec::Core::RakeTask.new(:old) do |task|
```

Does it work for you w/o shellescaping the test pattern?

**Comment by myronmarston** [comment]
I used `git bisect` to track down the source of the issue.  It is caused by 42f8ee9f72396bfa48897f6a883703c9d9e3bad6 (from #2002).  Because `RSpec::Core::RakeTask` has a `pattern` attribute which it _always_ includes in the `rspec` command and @xmik is also including one in `rspec_opts`, it's causing two pattern options to be passed, and interacting with the multi-pattern logic added in that commit.

@JonRowe, as the author of that change, do you want to dig into it some more?

**Comment by xmik** [comment]
@myronmarston, yes the 2 rake tasks (`new` and `old`), whenever used with rspec 3.3.0 or 3.4.0, work for me w/o shellescaping the test pattern. I use them as I wrote in readme. Full output:
```bash
gem-rspec-rake-task-reproduction$ BUNDLE_GEMFILE="./Gemfile.3-3-0" bundle exec rake old
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
/usr/bin/ruby2.2 -I/home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.3.2/lib:/home/ide/.gems/ruby/2.2.0/gems/rspec-support-3.3.0/lib /home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /ide/work/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb

Rspec::Rake::Task::Reproduction
  has a version number

Finished in 0.01411 seconds (files took 0.38891 seconds to load)
1 example, 0 failures
```
```bash
gem-rspec-rake-task-reproduction$ BUNDLE_GEMFILE="./Gemfile.3-3-0" bundle exec rake new
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
/usr/bin/ruby2.2 -I/home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.3.2/lib:/home/ide/.gems/ruby/2.2.0/gems/rspec-support-3.3.0/lib /home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern /ide/work/gem-rspec-rake-task-reproduction/test/\{unit,spec\}/\*\*/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html

Rspec::Rake::Task::Reproduction
  has a version number

Finished in 0.00262 seconds (files took 0.13197 seconds to load)
1 example, 0 failures
```
```bash
gem-rspec-rake-task-reproduction$ BUNDLE_GEMFILE="./Gemfile.3-4-0" bundle exec rake old
/usr/bin/ruby2.2 -I/home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.4.4/lib:/home/ide/.gems/ruby/2.2.0/gems/rspec-support-3.4.1/lib /home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html --pattern /ide/work/gem-rspec-rake-task-reproduction/test/{unit,spec}/**/*_spec.rb
No examples found.

Finished in 0.00081 seconds (files took 0.12372 seconds to load)
0 examples, 0 failures
```
```bash
gem-rspec-rake-task-reproduction$ BUNDLE_GEMFILE="./Gemfile.3-4-0" bundle exec rake new
/usr/bin/ruby2.2 -I/home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.4.4/lib:/home/ide/.gems/ruby/2.2.0/gems/rspec-support-3.4.1/lib /home/ide/.gems/ruby/2.2.0/gems/rspec-core-3.4.4/exe/rspec --pattern /ide/work/gem-rspec-rake-task-reproduction/test/\{unit,spec\}/\*\*/\*_spec.rb --tty --color --format documentation --format h --out ./rspec.html

Rspec::Rake::Task::Reproduction
  has a version number

Finished in 0.0033 seconds (files took 0.26552 seconds to load)
1 example, 0 failures

```
My environment is:
```bash
gem-rspec-rake-task-reproduction$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]
```

**Comment by JonRowe** [comment]
Your example repo fails the same way for me on `3.3.0` too btw, but can you give #2305 a chance to see if it fixes your issue?

**Comment by xmik** [comment]
Yes, it fixes my issue.
