### ISSUE TITLE
Backtrace, Can't filter out .rbenv lines

### ISSUE THREAD

**Issue by seyonv** [rspec/rspec-core#2332]
I can't get rid of the .rbenv lines from my backtrace. I've tried using exclusion patterns and going 
through notes in [issue 745](https://github.com/rspec/rspec-core/issues/754) but I haven't had any luck.

One thing I noticed is that this latest application uses Ruby 2.2.5 and a similar application (same spec_helper, rails_helper, .rspec) using Ruby 2.2.2 does not have this problem.

If I use guard, the problem does not exist either and the backtrace is better filtered. 

Backtrace from running $bundle exec rspec spec
```
/Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:656:in `method_missing'
  /Users/seyonvasantharajan/Desktop/whats_your_plan/spec/features/full_goalsetting_spec.rb:165:in `block (3 levels) in <top (required)>'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `module_exec'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `subclass'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
  /Users/seyonvasantharajan/Desktop/whats_your_plan/spec/features/full_goalsetting_spec.rb:149:in `block (2 levels) in <top (required)>'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `module_exec'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `subclass'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
  /Users/seyonvasantharajan/Desktop/whats_your_plan/spec/features/full_goalsetting_spec.rb:57:in `block in <top (required)>'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `module_exec'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `subclass'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
  /Users/seyonvasantharajan/Desktop/whats_your_plan/spec/features/full_goalsetting_spec.rb:12:in `<top (required)>'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/bin/rspec:23:in `load'
  /Users/seyonvasantharajan/.rbenv/versions/2.2.5/bin/rspec:23:in `<top (required)>'
```

spec_helper.rb

```
require 'capybara/rspec'
# require 'capybara/email/rspec'
require 'capybara/poltergeist'
require 'capybara-screenshot/rspec'
require 'should_not/rspec'

Capybara.javascript_driver = :poltergeist

RSpec.configure do |config|
  
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    expectations.syntax = :expect
  end
  config.before(:all) do
    FactoryGirl.reload
  end
  config.backtrace_exclusion_patterns << /\/Users\/seyonvasantharajan\/Desktop\/whats_your_plan\/\/spec\/features\//

end
```

**Comment by JonRowe** [comment]
What happens if you add this:
```Ruby
 config.backtrace_exclusion_patterns << %r{/Users/seyonvasantharajan/\.rbenv/}
```

**Comment by seyonv** [comment]
Whoah, that seems to have worked for cases where there's no dumb error. If I put a random letter "g",
the above stacktrace still persist with the two below lines at the top. Completely fine if I remove the g and there's no mention of .rbenv

```
bundler: failed to load command: rspec (/Users/seyonvasantharajan/.rbenv/versions/2.2.5/bin/rspec)
NameError: undefined local variable or method `g' for #<Class:0x007fd1698c82e0>
``

On another note(for my understanding), when I delete the line you gave me and there's no "g", .rbenv no longer appears which is interestingty

**Comment by JonRowe** [comment]
Thats bundler preventing RSpec from running at all, we've recently improved that but it's yet to be released.

**Comment by seyonv** [comment]
Ah. Thanks so much Jon!
