### ISSUE TITLE
Improve raise_error failure message for mismatched regex

### ISSUE THREAD

**Issue by roysc** [rspec/rspec-core#2357]
Minimal example:
```ruby
class Foo
  def self.foo
    raise "bar"
  end
end

RSpec.describe Foo do
  describe '#foo' do
    subject { Foo.foo }
    it { is_expected.to raise_error(/quux/) }
  end
end
```

Running:
```
$ rspec rspec_raise.rb 
F

Failures:

  1) Foo#foo 
     Failure/Error: raise "bar"

     RuntimeError:
       bar
     # ./rspec_raise.rb:3:in `foo'
     # ./rspec_raise.rb:9:in `block (3 levels) in <top (required)>'
     # ./rspec_raise.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.00062 seconds (files took 0.22821 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./rspec_raise.rb:10 # Foo#foo 
```
Issue:
====
The output should specifically mention that, while an error was raised, the message does not match what we expected.

**Comment by roysc** [comment]
User error. I had to use a block in the expectation:
```
    expect { Foo.foo }.to raise_error(/quux/) }
```
