### ISSUE TITLE
reset properties after rspec runner

### ISSUE THREAD

**Issue by roaldle** [rspec/rspec-core#2399]
I'm trying to test different docker containers with different rspec test files with the help of runner.
The first test goes fine but when the second one starts the :container_id property isn't replaced. Therefore I do the second tests on the wrong container.

I start the script. I clone the rspec configuration. Start the tests on the first container where I ask for the image id and set it as a property. Afterwards I do the tests.
I reset the rspec and put the original config back. The second tests are started where I get the id of the container again en set is as a property. When the second tests start the container id property is still the same.

When I execute the tests with rspec command it works.

**Verifier script**
```ruby
require 'rspec/core'
require 'docker'
require 'serverspec'

orig_config = RSpec.configuration.clone
RSpec::Core::Runner.run(["nginx_spec.rb"])
RSpec.reset
RSpec.configuration = orig_config
RSpec::Core::Runner.run(["fpm_spec.rb"])

``` 

**fpm container test**
```ruby
require 'serverspec'
require 'docker'

RSpec.configure do |c|
  c.formatter = :documentation
  @container = Docker::Container.get("phpfpm_fpm_1")
  set :os, family: :debian
  set :backend, :docker
  p 'container id'
  p @container.id
  set :docker_container, @container.id
end

describe 'fpm' do
  describe command("php-fpm -i | grep -i apc") do
    its(:stdout) { should contain("apcu") }
    its(:stdout) { should contain("APCu Support => Enabled") }
  end
end

```

**nginx container test**
```ruby
require 'serverspec'
require 'docker'

RSpec.configure do |c|
  c.formatter = :documentation
  @container = Docker::Container.get("phpfpm_nginx_1")
  set :os, family: :debian
  set :backend, :docker
  p 'container id'
  p @container.id
  set :docker_container, @container.id
end

describe "nginx" do
  describe package('nginx') do
    it { should be_installed }
  end

  describe service('nginx') do
    it { should be_enabled   }
    it { should be_running   }
  end

  describe port(80) do
    it { should be_listening }
  end

  describe command('nginx -t') do
    its(:exit_status) { should eq 0 }
  end
end
```

I see what id is being used when in the docker events. 
**Output from docker events when the verifier is executed**
```
2017-03-08T23:27:58.273810269+01:00 container exec_create: /bin/sh -c dpkg-query -f '${Status}' -W nginx | grep -E '^(install|hold) ok installed$' ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.279236125+01:00 container exec_start: /bin/sh -c dpkg-query -f '${Status}' -W nginx | grep -E '^(install|hold) ok installed$' ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.367766677+01:00 container exec_create: /bin/sh -c ls /etc/rc3.d/ | grep -- '^S..nginx$' || grep '^ *start on' /etc/init/nginx.conf ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.370699556+01:00 container exec_start: /bin/sh -c ls /etc/rc3.d/ | grep -- '^S..nginx$' || grep '^ *start on' /etc/init/nginx.conf ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.461371383+01:00 container exec_create: /bin/sh -c service nginx status ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.467091107+01:00 container exec_start: /bin/sh -c service nginx status ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.568177141+01:00 container exec_create: /bin/sh -c netstat -tunl | grep -- :80\  ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.570896762+01:00 container exec_start: /bin/sh -c netstat -tunl | grep -- :80\  ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.657063490+01:00 container exec_create: /bin/sh -c nginx -t ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.663052009+01:00 container exec_start: /bin/sh -c nginx -t ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.760111204+01:00 container exec_create: /bin/sh -c php-fpm -i | grep -i apc ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
2017-03-08T23:27:58.763334854+01:00 container exec_start: /bin/sh -c php-fpm -i | grep -i apc ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a (com.docker.compose.config-hash=23802571484277ced64f75f7fcc46608a739081f2fc6e86483b4674e3d89f7b9, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=phpfpm, com.docker.compose.service=nginx, com.docker.compose.version=1.11.2, image=docker-registry.wgp.dev:5000/wgp-nginx, name=phpfpm_nginx_1)
```

**Output when executing verifier script** 
```
"container id"
"ce0328502793eb1ec2bcb56cbcd9952751a9aaf83e891d0aa85c286ae35c157a"

nginx
  Package "nginx"
    should be installed
  Service "nginx"
    should be enabled
    should be running
  Port "80"
    should be listening
  Command "nginx -t"
    exit_status
      should eq 0

Finished in 0.49167 seconds (files took 0.58495 seconds to load)
5 examples, 0 failures

"container id"
"302225349bf40a13e86ccf14b93e7c587b5b503ab8594c271d47fac1c4fa6e63"

fpm
  Command "php-fpm -i | grep -i apc"
    stdout
      should contain "apcu" (FAILED - 1)
    stdout
      should contain "APCu Support => Enabled" (FAILED - 2)

Failures:

  1) fpm Command "php-fpm -i | grep -i apc" stdout should contain "apcu"
     Failure/Error: its(:stdout) { should contain("apcu") }
       expected "" to contain "apcu"

     # ./fpm_spec.rb:16:in `block (3 levels) in <top (required)>'
     # verifier.rb:9:in `<main>'

  2) fpm Command "php-fpm -i | grep -i apc" stdout should contain "APCu Support => Enabled"
     Failure/Error: its(:stdout) { should contain("APCu Support => Enabled") }
       expected "" to contain "APCu Support => Enabled"

     # ./fpm_spec.rb:17:in `block (3 levels) in <top (required)>'
     # verifier.rb:9:in `<main>'

Finished in 0.10598 seconds (files took 1.08 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./fpm_spec.rb:16 # fpm Command "php-fpm -i | grep -i apc" stdout should contain "apcu"
rspec ./fpm_spec.rb:17 # fpm Command "php-fpm -i | grep -i apc" stdout should contain "APCu Support => Enabled"
```

```RSpec.clear_examples```
Using clear examples instead of reset gives the same functionality

**Comment by JonRowe** [comment]
I'm not sure I understand your question, from your output your container id is changing, but this isn't an RSpec configured variable, its from serverspec or your code.

**Comment by roaldle** [comment]
Yes in the output the id is changing but the tests point to the wrong container even tho I set it to the right variable.
In the docker events it's clear that de id doesn't change.

**Comment by JonRowe** [comment]
I'm going to suggest you raise this with serverspec, I don't see how RSpec is responsible here...

**Comment by roaldle** [comment]
I thought it could be rspec because the spec files work independently when executed by rspec. 
But thanks anyway.
