### ISSUE TITLE
RSpec::Core::Formatters::ConsoleCodes (NameError) when using "after :all"

### ISSUE THREAD

**Issue by boonware** [rspec/rspec-core#2471]
I've hit a strange error with `rspec-core-3.5.4`. In a spec I have the following clean up code
```
    after :all do
        if (File.exist?(@repo)) then
            FileUtils.rm_rf(@repo)
        end
    end
```
where `@repo` is the path to a local Git repository that my tests were working with. With this code in the spec I get the error `fully_formatted': uninitialized constant RSpec::Core::Formatters::ConsoleCodes (NameError)`, and if I remove it the error goes away. Any idea what's causing this? I'm scratching my head to see how this simple directory clean-up is causing this error.

Full stacktrace is below:
```
/home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/formatters/exception_presenter.rb:75:in `fully_formatted': uninitialized constant RSpec::Core::Formatters::ConsoleCodes (NameError)
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:163:in `notify_non_example_exception'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:368:in `rescue in run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:366:in `run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:507:in `block in run_owned_hooks_for'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:506:in `each'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:506:in `run_owned_hooks_for'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:459:in `run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:574:in `block in run_after_context_hooks'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:573:in `run_after_context_hooks'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:600:in `run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `map'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/jenkins/.gem/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/jenkins/.gem/bin/rspec:23:in `load'
	from /home/jenkins/.gem/bin/rspec:23:in `<main>'
	from /home/jenkins/.gem/bin/ruby_executable_hooks:15:in `eval'
	from /home/jenkins/.gem/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by JonRowe** [comment]
Congratulations! You found a bug! Conveniently if you upgrade to the latest version you'll see this has already been fixed :)
