### ISSUE TITLE
Test failures with ruby 2.5.0

### ISSUE THREAD

**Issue by graaff** [rspec/rspec-core#2488]
With ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux] I'm seeing the following test failures with the released version of 3.7.0:

```
  1) RSpec behaves like library wide checks issues no warnings when the spec files are loaded
     Failure/Error: @example_group_instance.instance_exec(self, &@example_block)
     
       expected: ["", "", 0]
            got: ["", "/var/tmp/portage/dev-ruby/rspec-core-3.7.0/work/ruby25/rspec-core-3.7.0/spec/rspec/core/metadat...y25/rspec-core-3.7.0/spec/rspec/core_spec.rb:250: warning: assigned but unused variable - group", 0]
     
       (compared using ==)
     Shared Example Group: "library wide checks" called from ./spec/rspec/core_spec.rb:31
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  2) config block hook filtering when hooks are defined after a group has been defined applies only to groups with matching metadata
     Failure/Error:
       expect(sequence).to eq [
         :before_cont_1, :before_cont_2,
         :around_before_ex, :before_ex_1, :before_ex_2, :ex_1, :after_ex_1, :after_ex_2, :around_after_ex,
         :around_before_ex, :before_ex_1, :before_ex_2, :ex_2, :after_ex_1, :after_ex_2, :around_after_ex,
         :after_cont_1, :after_cont_2
       ]
     
       expected: [:before_cont_1, :before_cont_2, :around_before_ex, :before_ex_1, :before_ex_2, :ex_1, :after_ex_1, :...ex_1, :before_ex_2, :ex_2, :after_ex_1, :after_ex_2, :around_after_ex, :after_cont_1, :after_cont_2]
            got: [:before_cont_1, :before_cont_2, :before_cont_1, :before_cont_2, :around_before_ex, :before_ex_1, :be...ter_ex_1, :after_ex_2, :around_after_ex, :after_cont_1, :after_cont_2, :after_cont_1, :after_cont_2]
     
       (compared using ==)
     
       Diff:
       @@ -1,5 +1,7 @@
        [:before_cont_1,
         :before_cont_2,
       + :before_cont_1,
       + :before_cont_2,
         :around_before_ex,
         :before_ex_1,
         :before_ex_2,
       @@ -7,6 +9,10 @@
         :after_ex_1,
         :after_ex_2,
         :around_after_ex,
       + :after_cont_1,
       + :after_cont_2,
       + :before_cont_1,
       + :before_cont_2,
         :around_before_ex,
         :before_ex_1,
         :before_ex_2,
       @@ -14,6 +20,8 @@
         :after_ex_1,
         :after_ex_2,
         :around_after_ex,
       + :after_cont_1,
       + :after_cont_2,
         :after_cont_1,
         :after_cont_2]
     # ./spec/rspec/core/hooks_filtering_spec.rb:78:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  3) config block hook filtering when hooks are defined after a group has been defined only runs context hooks around the highest level group with matching filters
     Failure/Error: expect(sequence).to eq [:before_context, :before_hook, :example, :after_hook, :after_context]
     
       expected: [:before_context, :before_hook, :example, :after_hook, :after_context]
            got: [:before_context, :before_hook, :before_hook, :example, :after_hook, :after_hook, :after_context]
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,8 @@
       -[:before_context, :before_hook, :example, :after_hook, :after_context]
       +[:before_context,
       + :before_hook,
       + :before_hook,
       + :example,
       + :after_hook,
       + :after_hook,
       + :after_context]
     # ./spec/rspec/core/hooks_filtering_spec.rb:189:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  4) config block hook filtering when hooks are defined after a group has been defined still applies
     Failure/Error:
       expect(sequence).to eq [
         :before_cont_1, :before_cont_2,
         :around_before_ex, :before_ex_1, :before_ex_2, :ex_1, :after_ex_1, :after_ex_2, :around_after_ex,
         :around_before_ex, :before_ex_1, :before_ex_2, :ex_2, :after_ex_1, :after_ex_2, :around_after_ex,
         :after_cont_1, :after_cont_2
       ]
     
       expected: [:before_cont_1, :before_cont_2, :around_before_ex, :before_ex_1, :before_ex_2, :ex_1, :after_ex_1, :...ex_1, :before_ex_2, :ex_2, :after_ex_1, :after_ex_2, :around_after_ex, :after_cont_1, :after_cont_2]
            got: [:before_cont_1, :before_cont_2, :before_cont_1, :before_cont_2, :around_before_ex, :before_ex_1, :be...ter_ex_1, :after_ex_2, :around_after_ex, :after_cont_1, :after_cont_2, :after_cont_1, :after_cont_2]
     
       (compared using ==)
     
       Diff:
       @@ -1,5 +1,7 @@
        [:before_cont_1,
         :before_cont_2,
       + :before_cont_1,
       + :before_cont_2,
         :around_before_ex,
         :before_ex_1,
         :before_ex_2,
       @@ -7,6 +9,10 @@
         :after_ex_1,
         :after_ex_2,
         :around_after_ex,
       + :after_cont_1,
       + :after_cont_2,
       + :before_cont_1,
       + :before_cont_2,
         :around_before_ex,
         :before_ex_1,
         :before_ex_2,
       @@ -14,6 +20,8 @@
         :after_ex_1,
         :after_ex_2,
         :around_after_ex,
       + :after_cont_1,
       + :after_cont_2,
         :after_cont_1,
         :after_cont_2]
     # ./spec/rspec/core/hooks_filtering_spec.rb:34:in `block (3 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  5) RSpec::Core::Example#run leaves raised exceptions unmodified (GH-1103)
     Failure/Error: expect(actual.__id__).to eq(exception.__id__)
     
       expected: 47445621819560
            got: 47445621797760
     
       (compared using ==)
     # ./spec/rspec/core/example_spec.rb:519:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'

  6) Module#define_method is still a private method
     Failure/Error: expect { a_module.define_method(:name) { "implementation" } }.to raise_error NoMethodError
       expected NoMethodError but nothing was raised
     # ./spec/rspec/core/memoized_helpers_spec.rb:636:in `block (2 levels) in <module:Core>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by myronmarston** [comment]
I'm working on fixing this, but it's worth noting that some of the failures are due to a subtle regression in 2.5:

https://bugs.ruby-lang.org/issues/14045#note-5
