### ISSUE TITLE
If the test code is CP 932 and Japanese is included in failure / error, Encoding::CompatibilityError

### ISSUE THREAD

**Issue by hitanaka156** [rspec/rspec-core#2543]
Failure/Error occurs when magic comment of test code is set to CP932 in rspec-core-3.7.1, and Encoding::CompatibilityError occurs if the error content contains Japanese.

If you change the magic comment of "./rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb" to CP 932, you can avoid the error, but are there any other countermeasures?

> bundler: failed to load command: rspec (/opt/project/vendor/bundler/ruby/2.4.0/bin/rspec)
> Encoding::CompatibilityError: incompatible character encodings: Windows-31J and UTF-8
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:79:in `join'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:79:in `fully_formatted'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:200:in `fully_formatted'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each_with_index'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:175:in `block in finish'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
>   /opt/project/vendor/bundler/ruby/2.4.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
>   /opt/project/vendor/bundler/ruby/2.4.0/bin/rspec:22:in `load'
>   /opt/project/vendor/bundler/ruby/2.4.0/bin/rspec:22:in `<top (required)>'
> /opt/project/vendor/bundler/ruby/2.4.0/gems/configatron-4.5.1/lib/configatron/store.rb:51:in `store': wrong number of arguments (given 0, expected 2) (ArgumentError)
>         from /opt/project/vendor/bundler/ruby/2.4.0/gems/cover_me-1.2.0/lib/cover_me/results.rb:14:in `merge_results!'
>         from /opt/project/vendor/bundler/ruby/2.4.0/gems/cover_me-1.2.0/lib/cover_me.rb:44:in `block in <top (required)>'

> $ ruby -v
> ruby 2.4.0p0 (2016-12-24 revision 57164) [powerpc-aix6.1.0.0]
> $ rspec --version
> RSpec 3.7
>   - rspec-core 3.7.1
>   - rspec-expectations 3.7.0
>   - rspec-mocks 3.7.0
>   - rspec-rails 3.7.2
>   - rspec-support 3.7.0

**Comment by JonRowe** [comment]
Apologies, our encoding logic is supposed to handle such scenarios more gracefully than this, I will look into it.

**Comment by benoittgt** [comment]
Hello

I was trying to understand this error while watching for https://github.com/rspec/rspec-core/issues/2570

For the moment I see an issue here `lib/rspec/core/formatters/exception_presenter.rb:83`

```
2.5.1 :045 > lines[0]
 => "Output \x{E383}\x{86E3}\x{82B9}\x{E383}\x{88E5}\xAE\x{9FE8}\xA1\x{8CE7}\xB5\x{90E6}\x{9E9C}\x{E381}\xAE\x{E696}\x{87E5}\xAD\x{97E5}\x{8897}\x{E381}\xAB\x{E381}\xAF\x{E383}\xA1\x{E383}\x{83E3}\x{82BB}\x{E383}\xBC\x{E382}\xB8\x{E381}\x{8CE5}\x{87BA}\x{E58A}\x{9BE3}\x{8195}\x{E382}\x{8CE3}\x{828B}\x{E381}\x{93E3}\x{81A8}"
2.5.1 :046 > lines[1]
 => #<RSpec::Support::EncodedString:0x00007fad0479a410 @encoding=#<Encoding:UTF-8>, @source_encoding=#<Encoding:UTF-8>, @string="\e[31mFailure/Error: msg.include?(\"テスト実行結果\".encode(\"CP932\")).should be_truthy\e[0m">
2.5.1 :047 > [lines[0] + lines[1]].join("/n")
Traceback (most recent call last):
       16: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:166:in `finish'
       15: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:186:in `close_after'
       14: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:170:in `block in finish'
       13: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:200:in `notify'
       12: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:200:in `each'
       11: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:201:in `block in notify'
       10: from /Users/bti/code/rspec-core/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
        9: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
        8: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `each_with_index'
        7: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `each'
        6: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
        5: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:200:in `fully_formatted'
        4: from /Users/bti/code/rspec-core/lib/rspec/core/formatters/exception_presenter.rb:78:in `fully_formatted'
        3: from /Users/bti/code/rspec-core/lib/rspec/core/formatters/exception_presenter.rb:90:in `fully_formatted_lines'
        2: from (irb):47:in `fully_formatted_lines'
        1: from (irb):47:in `+'
Encoding::CompatibilityError (incompatible character encodings: Windows-31J and UTF-8)
```

I didn't go deeper at the moment. While to try to dig into when I will have more times.

**Comment by benoittgt** [comment]
I read a little bit of Encoding part of RSpect Support. Maybe their is a link. 🤷‍♂️

**Comment by benoittgt** [comment]
Ok with this it works:

```diff
--- a/lib/rspec/core/formatters/exception_presenter.rb
+++ b/lib/rspec/core/formatters/exception_presenter.rb
@@ -81,7 +81,7 @@ module RSpec

         def fully_formatted_lines(failure_number, colorizer)
           lines = [
-            description,
+            encoded_string(description),
```

With this repro script from https://github.com/rspec/rspec-core/issues/2570

```ruby
#-*- coding: CP932 -*-
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec-core", path: "~/code/rspec-core"
  gem "rspec-support", path: "~/code/rspec-support"
end

puts "Ruby version is: #{RUBY_VERSION}"

require 'rspec/autorun'

RSpec.describe 'Output' do
  it "テスト実行結果の文字列にはメッセージが出力されること" do
    msg = ""
    msg.include?("テスト実行結果".encode("CP932")).should be_truthy
  end
end
```

I had
```
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.16.2
Using rspec-support 3.9.0.pre from source at `~/code/rspec-support`
Using rspec-core 3.9.0.pre from source at `~/code/rspec-core`
Ruby version is: 2.5.1
F

Traceback (most recent call last):
	20: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:24:in `block in autorun'
	19: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:38:in `perform_at_exit'
	18: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:45:in `invoke'
	17: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:71:in `run'
	16: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:87:in `run'
	15: from /Users/bti/code/rspec-core/lib/rspec/core/runner.rb:110:in `run_specs'
	14: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:76:in `report'
	13: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:166:in `finish'
	12: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:186:in `close_after'
	11: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:170:in `block in finish'
	10: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:200:in `notify'
	 9: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:200:in `each'
	 8: from /Users/bti/code/rspec-core/lib/rspec/core/reporter.rb:201:in `block in notify'
	 7: from /Users/bti/code/rspec-core/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	 6: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	 5: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `each_with_index'
	 4: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:113:in `each'
	 3: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
	 2: from /Users/bti/code/rspec-core/lib/rspec/core/notifications.rb:200:in `fully_formatted'
	 1: from /Users/bti/code/rspec-core/lib/rspec/core/formatters/exception_presenter.rb:79:in `fully_formatted'
/Users/bti/code/rspec-core/lib/rspec/core/formatters/exception_presenter.rb:79:in `join': incompatible character encodings: Windows-31J and UTF-8 (Encoding::CompatibilityError)
```

With the change from the diff:
```
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.16.2
Using rspec-support 3.9.0.pre from source at `~/code/rspec-support`
Using rspec-core 3.9.0.pre from source at `~/code/rspec-core`
Ruby version is: 2.5.1
F

Failures:

  1) Output 繝?せ繝亥ｮ溯｡檎ｵ先棡縺ｮ譁?ｭ怜?縺ｫ縺ｯ繝｡繝?そ繝ｼ繧ｸ縺悟?蜉帙＆繧後ｋ縺薙→
     Failure/Error: msg.include?("テスト実行結果".encode("CP932")).should be_truthy

     NameError:
       undefined local variable or method `be_truthy' for #<RSpec::ExampleGroups::Output:0x00007fc37af9e0f8>
     # repro_script.rb:25:in `block (2 levels) in <main>'

Finished in 0.00231 seconds (files took 0.04661 seconds to load)
1 example, 1 failure

Failed examples:

rspec repro_script.rb:23 # Output テスト実行結果の文字列にはメッセージが出力されること
```

I will try to make a PR with a test to validate this behavior.

**Comment by benoittgt** [comment]
It should be fixed with #2575

Do you think you can try it @hitanaka156?

We will reopen the issue if it is not fixed.

**Comment by hitanaka156** [comment]
Thank you for investigating.
However, the problem was not solved even if it was corrected by # 2575.
In my environment, Encoding :: CompatibilityError still occurs.

**Comment by benoittgt** [comment]
Rah 😔 thanks a lot for the feedback @hitanaka156 
Do you think you can provide a reproduce script similar to https://github.com/rspec/rspec-core/issues/2543#issuecomment-430419757? Also if you can specify your environment: OS, version, shell, encoding.

**Comment by pirj** [comment]
Is this still problematic @hitanaka156 ?

**Comment by JonRowe** [comment]
It will be @pirj
