### ISSUE TITLE
Undefined method `shellescape' for Pathname

### ISSUE THREAD

**Issue by hakunin** [rspec/rspec-core#2550]
###  Undefined method `shellescape' for Pathname
```
$ rspec --seed 61123 --bisect
Running via Spring preloader in process 20483
Bisect started using options: "--seed 61123"
Running suite to find failures...
/Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/shell_escape.rb:20:in `escape': undefined method `shellescape' for #<Pathname:/Users/michal/dev/ht2/lib> (NoMethodError)
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:154:in `block in load_path'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:154:in `map'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:154:in `load_path'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:26:in `command_for'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:68:in `block in run_locations'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/server.rb:27:in `capture_run_results'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:67:in `run_locations'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/runner.rb:50:in `original_results'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/example_minimizer.rb:114:in `block in prep'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/example_minimizer.rb:151:in `track_duration'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/example_minimizer.rb:113:in `prep'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/example_minimizer.rb:17:in `find_minimal_repro'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/coordinator.rb:37:in `block (2 levels) in bisect'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/server.rb:18:in `run'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/coordinator.rb:32:in `block in bisect'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/coordinator.rb:31:in `bisect'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/bisect/coordinator.rb:19:in `bisect_with'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/invocations.rb:32:in `call'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:69:in `run'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /Users/michal/.rvm/gems/ruby-2.4.4/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
        from /Users/michal/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/michal/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

### Your environment
* Ruby version: 2.4.4
* rspec-core version: 3.7.1

### Steps to reproduce
No idea, but it fails only with biseect.

### Expected behavior
Working bisect

### Actual behavior
Exception

**Comment by hakunin** [comment]
That did the trick. Tried simply stopping spring before but it was in the binstub.
```
DISABLE_SPRING=1  rspec --bisect --seed 61123
```

It might help time wise if I could run bisect with spring, but at least I can run it now. Thanks!

**Comment by myronmarston** [comment]
We can’t help how spring breaks things. We load shellwords from the ruby stdlib; if a tool like spring breaks stdlib requires there’s not much we can do about that :-(.
