### ISSUE TITLE
Japanese letters get garbled in error messages.

### ISSUE THREAD

**Issue by shusuke-nakamura** [rspec/rspec-core#2570]
We are using rspec - core - 3.7.1, and tring to test files which encodings are set as 'CP932'.
When we run failing tests, Japanese letters in error messages get garbled.

For instance, if we run the test code below.

```ruby
it "テスト実行結果の文字列には#{check_result}のメッセージが出力されること" do
  @msg.include?("【テスト実行結果】...#{check_result}".encode("CP932")).should be_truthy
end
```

The excution result would look like this.

```
Failures:

1) CheckTable#check_character 整合性チェックOKの場合 behaves like examples_check_character テスト実行 結果の文字列にはOKのメッセージが出力されること
Failure/Error: @msg.include?("縲舌ユ繧ｹ繝亥ｮ溯｡檎ｵ先棡縲?...#{check_result}".encode("CP932")).should be_truthy

expected: truthy value
got: false
```

In the error message,  【テスト実行結果】 became '縲舌ユ繧ｹ繝亥ｮ溯｡檎ｵ先棡縲?'.

Is there anyway to fix this issue?

**Comment by JonRowe** [comment]
Are you able to pass the test? (e.g is it the expectation code thats wrong too? or just the differ?)

**Comment by shusuke-nakamura** [comment]
Thanks for the quick response.
 Yes, we are able to pass the test. As I mentioned, this incident only happens in the error messages.

**Comment by shusuke-nakamura** [comment]
Here is the reproduction script.

````ruby
#-*- coding: CP932 -*-
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.7.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"

require 'rspec/autorun'

RSpec.describe 'Output' do
  it "テスト実行結果の文字列にはメッセージが出力されること" do
    msg = ""
    msg.include?("テスト実行結果".encode("CP932")).should be_truthy
  end
end
```

The result of the code above looks like this.

```console
Failures:

  1) Output テスト実行結果の文字列にはメッセージが出力されること
     Failure/Error: msg.include?("?e?X?g???s????".encode("CP932")).should be_truthy

       expected: truthy value
            got: false
     # rspec_report.rb:10:in `block (2 levels) in <main>'
```
 If we pass the expected value which is `テスト実行結果`  to the local variable `msg`, we are able to pass the test.

**Comment by benoittgt** [comment]
Hello @shusuke-nakamura 

I'm not a professional of encoding but I have a different error when I try to run your script on ruby-2.4.4 and ruby-2.5.1.

```
$ ruby repro_script.rb
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 1.16.2
Fetching diff-lcs 1.3
Fetching rspec-support 3.7.1
Installing rspec-support 3.7.1
Installing diff-lcs 1.3
Fetching rspec-core 3.7.1
Fetching rspec-expectations 3.7.0
Fetching rspec-mocks 3.7.0
Installing rspec-core 3.7.1
Installing rspec-mocks 3.7.0
Installing rspec-expectations 3.7.0
Fetching rspec 3.7.0
Installing rspec 3.7.0
Ruby version is: 2.4.4
F

/Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:79:in `join': incompatible character encodings: Windows-31J and UTF-8 (Encoding::CompatibilityError)
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:79:in `fully_formatted'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:200:in `fully_formatted'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each_with_index'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:175:in `block in finish'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:38:in `perform_at_exit'
	from /Users/bti/.rvm/gems/ruby-2.4.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:24:in `block in autorun'
```

Who link to another RSpec issue: https://github.com/rspec/rspec-core/issues/2543
Also: https://github.com/elizagamedev/wolftrans/issues/2

Maybe looking at this one can help: https://tickets.puppetlabs.com/browse/PUP-8368

I will look at https://github.com/rspec/rspec-core/issues/2543 first then go back on this one.

**Comment by benoittgt** [comment]
I'm able to reproduce with:

```diff
--- a/lib/rspec/core/formatters/exception_presenter.rb
+++ b/lib/rspec/core/formatters/exception_presenter.rb
@@ -1,4 +1,4 @@
-# encoding: utf-8
+# encoding: CP932
```

```
Failures:

  1) Output テスト実行結果の文字列にはメッセージが出力されること
     Failure/Error: msg.include?("�e�X�g���s����".encode("CP932")).should be_truthy

     NameError:
       undefined local variable or method `be_truthy' for #<RSpec::ExampleGroups::Output:0x00007f91cecc0a30>
     # repro_script.rb:25:in `block (2 levels) in <main>'

Finished in 0.00358 seconds (files took 0.04909 seconds to load)
1 example, 1 failure

Failed examples:

rspec repro_script.rb:23 # Output テスト実行結果の文字列にはメッセージが出力されること
```

**Comment by shusuke-nakamura** [comment]
@benoittgt 
Thank you for your response.
Yes, I am using windows.
I appreciate your further research on this matter.

**Comment by benoittgt** [comment]
It should be fixed with https://github.com/rspec/rspec-core/pull/2575

Do you think you can try it @shusuke-nakamura?
