### ISSUE TITLE
backtrace_formatter.rb - invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by MSP-Greg** [rspec/rspec-core#2650]
### Subject of the issue

While running bundler tests in ruby/ruby (currently done with Azure Pipelines running an Ubuntu job and a MacOS job), the following error appears:

```
All in rspec-core-3.8.2/lib/rspec/core/

backtrace_formatter.rb:61:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
backtrace_formatter.rb:61:in `block in matches?'
core/backtrace_formatter.rb:61:in `any?'
backtrace_formatter.rb:61:in `matches?'
backtrace_formatter.rb:55:in `exclude?'
backtrace_formatter.rb:50:in `backtrace_line'
backtrace_formatter.rb:37:in `block in format_backtrace'
backtrace_formatter.rb:37:in `map'
backtrace_formatter.rb:37:in `format_backtrace'
formatters/exception_presenter.rb:58:in `formatted_cause'
```

I work with trunk/master/2.7.0 and I've never come across this error before.  Anyone have any ideas?

### Your environment
* Ruby version: master/trunk
* rspec-core version: 3.8.2

### Steps to reproduce

Run Ruby Azure Pipelines tests, the 'bundler' jobs'...

**Comment by JonRowe** [comment]
:wave: Will need a bit more information to help here, this is likely an encoding error with the regular expression, so your config and command line usage would help

**Comment by MSP-Greg** [comment]
Jon,

I wanted to create an issue in case something else causes the same error.  Sometime I'll investigate more, but I've got a few other 'fires' that need attending...

**Comment by MSP-Greg** [comment]
I just ran the same tests on Appveyor, and I got the same error.  I briefly looked at the code:

https://github.com/rspec/rspec-core/blob/77dbc84657c5dc45e07a7fe0f5b02b4caeb6c9ad/lib/rspec/core/backtrace_formatter.rb#L8-L20

I may try and adjust the code and see if anything changes, but the only way I know how to repo it is running the bundler test suite with ruby-head/trunk.

There are a few parenthesis in the regex, and `?:` isn't used.  The Ruby docs for [`Rexgexp.union`](https://msp-greg.github.io/ruby_trunk/Core/Regexp.html#union-class_method) state that:

"The behavior is unspecified if any given pattern contains capture."

Not quite sure exactly what's meant by that...

**Comment by JonRowe** [comment]
> "The behavior is unspecified if any given pattern contains capture."

I've always taken that to read as, "don't expect your captures to line up correctly"

**Comment by MSP-Greg** [comment]
I haven't thought about possible solutions, but this may be due to how Azure Pipelines deals with ANSI escape sequences, which don't affect the displayed logs...

Ok to close.

**Comment by JonRowe** [comment]
(We know our Windows support isn't great, anything we can do to improve it is a good thing..)

**Comment by MSP-Greg** [comment]
You're testing on Appveyor (maybe add 2.6 or trunk?), so you're doing fine.  I wonder if [`String#scrub`](https://msp-greg.github.io/ruby_trunk/Core/String.html#scrub-instance_method) would help here?  Never used it.

**Comment by benoittgt** [comment]
> You're testing on Appveyor (maybe add 2.6 or trunk?), so you're doing fine.

At the moment we don't :/

https://github.com/rspec/rspec-core/blob/master/appveyor.yml#L34-L41

**Comment by JonRowe** [comment]
I'd like to see if 2.6 has this issue for us, or otherwise replicate it on appveyor, @benoittgt do you want to take care of that?

**Comment by MSP-Greg** [comment]
Bundler has some color 'add-ins' that are used in their testing, and the issue is only ocurring when bundler is tested as it exists in the ruby/ruby repo.

I'm assuming the code in question is only called when a backtrace needs to be formatted.

It may be a few days, but what I'll do is add a patch for `backtrace_formatter.rb` to the Azure Pipelines testing to filter the ANSI color code strings, and see if the error goes away.  As mentioned, this probably also involves how Azure Pipelines handles ANSI color code strings...

**Comment by pirj** [comment]
Since 2.7 is out, I've opened #2688 and it failed hard https://ci.appveyor.com/project/rspec/rspec-core/builds/30139185
Any volunteers to move this further?

**Comment by JonRowe** [comment]
Closing due to inactivity and Ruby 2.7 is long gone.
