### ISSUE TITLE
The error during tests execution

### ISSUE THREAD

**Issue by Riddlerrr** [rspec/rspec-core#2701]
### Subject of the issue
When I executed tests where raised custom Exception RSpec is failed with status 0.
Thus CI think that tests are ok and we have a false positive issue.

I faced with it in a real project which uses `connect-sdk-ruby` gem, [this exception](https://github.com/Ingenico-ePayments/connect-sdk-ruby/blob/c72f4c8289b883063e8773390dbd80173fb74c15/lib/ingenico/connect/sdk/communication_exception.rb) was raised.

### Your environment
* Ruby version: 2.6.5
* rspec-core version: latest master (revision da87aa0c5f25a6e6f2db6f0c8fb2a04625b80ac6)

### Steps to reproduce

1. Clone my repository https://github.com/Riddlerrr/rspec-exception-issue
2. Run `bundle exec rspec exception_spec.rb`

### Expected behavior
RSpec should print failures. For example:
```
Failures:

  1) Test exeption successfully output exeption
     Failure/Error: raise RuntimeError.new("RSpec error")
     
     RuntimeError:
       RSpec error
     # ./exception_spec.rb:20:in `block (2 levels) in <top (required)>'
```

### Actual behavior
```
bundler: failed to load command: rspec (/Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec)
NoMethodError: undefined method `cause' for "RSpec error":String
Did you mean?  case
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:98:in `final_exception'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:101:in `final_exception'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:46:in `formatted_cause'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:41:in `formatted_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:72:in `colorized_formatted_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:240:in `formatted_message_and_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:86:in `fully_formatted_lines'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:78:in `fully_formatted'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:200:in `fully_formatted'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `each'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `each_with_index'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:209:in `block in notify'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:208:in `each'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:208:in `notify'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:178:in `block in finish'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:194:in `close_after'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:174:in `finish'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:76:in `report'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:115:in `run_specs'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:89:in `run'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:71:in `run'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/exe/rspec:4:in `<top (required)>'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec:23:in `load'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec:23:in `<top (required)>'
```

**Comment by benoittgt** [comment]
Hello @Riddlerrr 

Thanks for your report. It seems https://github.com/Riddlerrr/rspec-exception-issue is private. Could you make it public?

Thanks

**Comment by Riddlerrr** [comment]
@benoittgt Oh, sure, sorry, didn't noticed. Done.

**Comment by JonRowe** [comment]
:wave: This is primarily an issue with `connect-sdk-ruby`, `cause` is a Ruby api they are overriding incorrectly, its supposed to return an exception not a string.

**Comment by Riddlerrr** [comment]
> we could probably fail saying that cause is broken here.

Yeah, It would be great!

**Comment by pirj** [comment]
Would you like to tackle that given all the necessary guidance will be provided @Riddlerrr ?

You may start by adding a guard statement:
```ruby
return exception unless exception.respond_to?(:cause)
```
[here](https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/formatters/exception_presenter.rb#L98) to see if it fixes it on your side, and later throw in an example [here](https://github.com/rspec/rspec-core/blob/master/spec/rspec/core/formatters/exception_presenter_spec.rb) of what happens when `connect-sdk-ruby` comes into play:
```ruby
let(:exception) do
  Class.new(String) do
    def backtrace
      # ...
    end
    def message
      # ...
    end
    # no `cause` defined
  end.new
end
```

**Comment by Riddlerrr** [comment]
Sorry guys, I was wrong. Rspec exits with status 1 so CI have to show a fail.
The problem is in our CI configuration. We run rspec like this `rspec || rspec --only-failures`.
The first `rspec` fails but don't fill failed tests file, so the second one thinks no failed present and exits with status 0.

It clearly nothing to do in `rspec-core` so I'm closing the issue.
Thanks everyone for your help ❤️

**Comment by JonRowe** [comment]
The error is still the wrong error, I'm working on a fix :)

**Comment by Riddlerrr** [comment]
Thank you for the fix!
