### ISSUE TITLE
after hooks with custom output_stream does not include failure summary

### ISSUE THREAD

**Issue by allcentury** [rspec/rspec-core#2801]
### Subject of the issue

The final output of rspec looks something like this:

```
Failures:

  1) additions returns 1
     Failure/Error: expect(3 - 1).to eq(-1)

       expected: -1
            got: 2

       (compared using ==)
     # report.rb:78:in `block (2 levels) in <main>'
\n
Finished in 0.00715 seconds (files took 0.15668 seconds to load)
2 examples, 1 failure

Failed examples:

rspec report.rb:77 # additions returns 1
```

However, that output is not available in any of the available `after(..)` hooks.  

### Your environment
* Ruby version: 2.6
* rspec-core version: 3.7

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.7.0" # Activate the gem and version you are reporting the issue against.
  gem "pry"
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

class Output
  attr_reader :messages
  def initialize
    @messages = ""
  end
  def puts(message = "")
    message += '\n'
    @messages += message
  end

  def closed?
    false
  end

  def flush
    Kernel.puts
    Kernel.puts "-------------"
    Kernel.puts"at flush"
    Kernel.puts "-------------"
    Kernel.puts @messages
  end
end

output = Output.new
RSpec.configure do |c|
  c.output_stream = output
  c.after(:each) do
    puts
    puts "-------------"
    puts "after_each"
    puts "-------------"
    puts output.messages
  end
  c.after(:suite) do
    puts
    puts "-------------"
    puts "after_suite"
    puts "-------------"
    puts output.messages
  end
  c.after(:all) do
    puts
    puts "-------------"
    puts "after_all"
    puts "-------------"
    puts output.messages
  end
end

RSpec.describe 'additions' do
  it 'returns 2' do
    expect(1 + 1).to eq(2)
  end

  it 'returns 1' do
    expect(3 - 1).to eq(-1)
  end
end
```

output:

```
[dev]antross:~/bt(rc=1) % ruby report.rb
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.1.4
Using coderay 1.1.3
Using method_source 1.0.0
Using rspec-support 3.7.1
Using diff-lcs 1.4.4
Using rspec-core 3.7.1
Using pry 0.13.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Ruby version is: 2.6.5

-------------
after_each
-------------

.
-------------
after_each
-------------

F
-------------
after_all
-------------


-------------
after_suite
-------------


-------------
at flush
-------------
\n
Failures:

  1) additions returns 1
     Failure/Error: expect(3 - 1).to eq(-1)

       expected: -1
            got: 2

       (compared using ==)
     # report.rb:78:in `block (2 levels) in <main>'
\n
Finished in 0.00715 seconds (files took 0.15668 seconds to load)
2 examples, 1 failure

Failed examples:

rspec report.rb:77 # additions returns 1
\n\n
```

### Expected behavior

I was hoping I would have access to the Failures output within a callback.

### Actual behavior

I don't have that.

Sorry for the lengthy reproduction example, this was hard for me to set up correctly.

**Comment by pirj** [comment]
Thanks for the detailed report.
`after` hook is part of an example, and is executed as part of it. Failures may happen in the `after` hook as well, and they would count towards failures from the example block itself.
You are probably looking for a [custom formatted](https://relishapp.com/rspec/rspec-core/v/3-9/docs/formatters/custom-formatters), it has [its own hooks](https://github.com/rspec/rspec-core/blob/fe3084758857f0714f05ada44a18f1dfe9bf7a7e/spec/rspec/core/reporter_spec.rb#L90), where you're probably looking for `example_failed`.
Still, it depends on what you are trying to achieve.
Welcome to our various support channels http://rspec.info/help/ to get guidance on how to build what you are working on.

**Comment by JonRowe** [comment]
The `dump_summary` hook in a custom formatter is probably what you want.
