### ISSUE TITLE
Ruby 3.1 error_highlight makes  `raise_error` specs fail

### ISSUE THREAD

**Issue by yahonda** [rspec/rspec-core#2930]
### Subject of the issue

Ruby 3.1 error_highlight makes  `raise_error` specs fail because the error message contains error highlights suggestions.

### Your environment
* Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
* rspec-core version: 3.10.1

### Steps to reproduce
- ruby31_error_highlight.rb
```ruby
require 'rspec'
require 'error_highlight'

Foo = Struct.new(:foo, :bar)
obj = Foo.new('FOO', 'BAR')

# This spec fails with Ruby 3.1.
describe "calling a missing method" do
  it "raises" do
    expect { obj[:baz] }.to raise_error(NameError, "no member 'baz' in struct")
  end
end

# This spec passes with Ruby 3.1 because the second argument is Regexp.
describe "calling a missing method" do
  it "raises" do
    expect { obj[:baz] }.to raise_error(NameError, /no member 'baz' in struct/)
  end
end
```

### Expected behavior
Both specs should pass.

### Actual behavior

```ruby
% rspec ruby31_error_highlight.rb
F.

Failures:

  1) calling a missing method raises
     Failure/Error: expect { obj[:baz] }.to raise_error(NameError, "no member 'baz' in struct")

       expected NameError with "no member 'baz' in struct", got #<NameError: no member 'baz' in struct

           expect { obj[:baz] }.to raise_error(NameError, "no member 'baz' in struct")
                       ^^^^^^
       Did you mean?  bar> with backtrace:
         # ./ruby31_error_highlight.rb:10:in `[]'
         # ./ruby31_error_highlight.rb:10:in `block (3 levels) in <top (required)>'
         # ./ruby31_error_highlight.rb:10:in `block (2 levels) in <top (required)>'
     # ./ruby31_error_highlight.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.0102 seconds (files took 0.06185 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./ruby31_error_highlight.rb:9 # calling a missing method raises

%
```

**Comment by JonRowe** [comment]
Please upgrade `rspec-expectations` to 3.10.2 which fixed this issue, closing as this is an issue with `rspec-expectations`.

**Comment by yahonda** [comment]
Thanks for the useful info.  Confirmed as fixed.

```
% gem update rspec-expectations
Updating installed gems
Updating rspec-expectations
Fetching rspec-expectations-3.10.2.gem
Successfully installed rspec-expectations-3.10.2
Parsing documentation for rspec-expectations-3.10.2
Installing ri documentation for rspec-expectations-3.10.2
Done installing documentation for rspec-expectations after 0 seconds
Parsing documentation for rspec-expectations-3.10.2
Done installing documentation for rspec-expectations after 0 seconds
Gems updated: rspec-expectations
% rspec ruby31_error_highlight.rb
..

Finished in 0.00213 seconds (files took 0.06463 seconds to load)
2 examples, 0 failures

%
```
