### ISSUE TITLE
doc_string which is the first argument of example, must be string object

### ISSUE THREAD

**Issue by eisukeyeongjo** [rspec/rspec-core#3072]
### doc_string which is the first argument of example, must be string object

RSpec example recognize the first argument as its description.
There might be no bad effect if first argument keeps string object.
But without check of the object type, it recognizes even symbol or hash object which set intended as metadata, as the description.
I submitted this issue for adding check for object type of description to avoid accepting non string description. 

### Your environment
* Ruby version: 3.3.0
* rspec-core version: 3.1.3

### Steps to reproduce

**prepare rspec test below**

```
$ vi test.rb
$ cat test.rb
```

```ruby
context do
  it :pending do
    # Only pending option without reason
    expect(true).to eq false
  end

  it pending: 'only pending option' do
    expect(true).to eq false   
  end  

  it 'description with option', pending: 'some reason' do
    expect(true).to eq false
  end
end
```

**execute rspec**

```
$ rspec test.rb --format documentation
```

### Expected behavior

all examples are pending

```
$ bundle exec rspec test.rb --format documentation


  is expected to eq false (PENDING: No reason given)
  is expected to eq false (PENDING: only pending option)
  description with option (PENDING: some reason)

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) is expected to eq false
     # No reason given
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:4:in `block (2 levels) in <top (required)>'

  2) is expected to eq false
     # only pending option
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:8:in `block (2 levels) in <top (required)>'

  3) description with option
     # some reason
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.01326 seconds (files took 0.08789 seconds to load)
3 examples, 0 failures, 3 pending

```

### Actual behavior

metadata is recognized as description and pending does not work, failing two examples

```
$ bundle exec rspec test.rb --format documentation


  pending (FAILED - 1)
  {:pending=>"only pending option"} (FAILED - 2)
  description with option (PENDING: some reason)

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) description with option
     # some reason
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:12:in `block (2 levels) in <top (required)>'

Failures:

  1) pending
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:4:in `block (2 levels) in <top (required)>'

  2) {:pending=>"only pending option"}
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.01369 seconds (files took 0.0876 seconds to load)
3 examples, 2 failures, 1 pending

Failed examples:

rspec ./test.rb:2 # pending
rspec ./test.rb:7 # {:pending=>"only pending option"}

```

### Related Pull Request
I proposed this new specification in the PR below,
After the discussion, we decided to add this in upcoming 4.x and add warning in 3.99

https://github.com/rspec/rspec-core/pull/3071

### What to do
- [ ] Add warning for upcoming breaking change in 4.0
- [ ] Add strict check for the doc_string of example

**Comment by pirj** [comment]
@JonRowe do you agree with the expected behaviour section here?
> doc_string which is the first argument of example, must be string object

It confuses me when the first argument is not a string and we accept it as metadata.
It seems to be a move in the wrong direction, bending to the pressure of existing specs that pass non-strings and expect that to work.

To me, the “must” in the “must be a string object” means we raise an argument error when it’s not.

In my defense, `it :pending` can become just `pending`, even though it’s just a special case, and `it :clean_db` doesn’t have/deserve such an alias.

I can foresee misuse and workarounds like `it “”, :clean_db do`.

I find it hard to justify the `it pending: “not implemented yet” do` as it gives no information on what wasn’t implemented exactly. But again, this is just a special case. Another example would be `it platform: :ios`, but that probably should be a context.

I’d love to see more examples of what we are going to break if we go with a more strict approach.

It’s more of a gut feeling, but going with accepting the first argument as metadata where it previously wasn’t, makes me uncomfortable when thinking of side effects that might be introduced by such metadata.

**Comment by pirj** [comment]
Sounds good, and no worries. Thanks for your contributions!
